Auto-generate README with tag information (#192)
Graylog2/graylog-docker pull request #199
Opened 2021-12-15 21:17 UTC by malcyon

Auto-generate the Readme so the releaser doesn't have to manually update each tag in the README.

(cherry picked from commit 44ec70953c28d90af5f493f6bb27779c01eeff7d)

2021-12-16 16:12 UTC, malcyon commented
Just dropping a reminder here for myself. They `jenkins.groovy` pipeline is still referencing the deleted `VERSION` and `                  VERSION_FORWARDER_PACKAGE` files. This will need to be updated before this is merged.

2021-12-17 09:06 UTC, thll requested changes
Found one thing, otherwise looks good.

After the release, this now needs a rebase and adjustment of the graylog patch version.
Also, I think the `VERSION_FORWARDER` file should be removed.

2021-12-27 16:35 UTC, malcyon commented on docker/forwarder/hooks/build
> +             --build-arg GRAYLOG_FORWARDER_PACKAGE_VERSION=`./release.py --get-forwarder-version` \
Okay, I've update the `version.yml` to reference the latest 4.0 release. I also removed the `VERSION_FORWARDER` file.

In the recommended change above, that's just renaming the BUILD_ARG variable. One name is as good as another to me. But if I change it here, then I have to change it in the `4.1` and `4.2` branches as well. So I'd just as soon leave it the way it is.

2022-01-04 10:35 UTC, thll approved these changes

2022-01-05 13:50 UTC, merged